### ISSUE TITLE
Redirecting to wrong URL from search bar

### ISSUE THREAD

**Issue by raysarinas** [ECE493W21T11/ualberta_path#72]
When we are on a details page, for example, `http://localhost:3000/instructor/john_raymond` and we go to the search bar and try to go to `ANTHR 464`, we are redirected to `http://localhost:3000/instructor/course/anthr464` instead of `http://localhost:3000/course/anthr464`. Just need to fix the path

**Comment by MXSH-Dev** [comment]
this is fixed, will be pushed later
